from django.urls import path
from .views import home, poblar_bd, vehiculo, vehiculo_tienda, vehiculo_ficha, index

from .views import about, all_facturas, all_products, carrito, contact, edit_product, editadmin, facture, ficha_product1_admin,ficha_product1_client,ficha_product2_admin,ficha_product2_client,ficha_product3_admin,ficha_product3_client,ficha_product4_admin,ficha_product4_client,ficha_product5_admin,ficha_product5_client,ficha_product6_admin,ficha_product6_client,Historial_de_compra, historial_ventas,home,impFactura,index_admin,index,login_admin,login,man_bod, man_prod, mockadmin,mon_compra, perfil, price, product_admin, product_anon, product_client,registro_usuarios,registro,useradmin,vehiculo_ficha,vehiculo_tienda,vehiculo

urlpatterns = [
    # path('', home, name="home"),
    # path('index', index, name="index"),
    # path('poblar_bd', poblar_bd, name="poblar_bd"),
    # path('vehiculo/<action>/<id>', vehiculo, name="vehiculo"),
    # path('vehiculo_tienda', vehiculo_tienda, name="vehiculo_tienda"),
    # path('vehiculo_ficha/<id>', vehiculo_ficha, name="vehiculo_ficha"),
    path('', index,name="index"),
    path('', login,name="login"),
    path('registro', registro,name="registro"),
    path('about',about ,name="about"),
    path('all_facturas', all_facturas,name="all_facturas"),
    path('all_products',all_products ,name="all_products"),
    path('carrito',carrito ,name="carrito"),
    path('contact',contact ,name="contact"),
    path('edit_product',edit_product ,name="edit_product"),
    path('editadmin',editadmin ,name="editadmin"),
    path('facture',facture ,name="facture"),
    path('ficha_product1_admin',ficha_product1_admin ,name="ficha_product1_admin"),
    path('ficha_product1_client',ficha_product1_client ,name="ficha_product1_client"),
    path('ficha_product2_admin',ficha_product2_admin ,name="ficha_product2_admin"),
    path('ficha_product2_client',ficha_product2_client ,name="ficha_product2_client"),
    path('ficha_product3_admin',ficha_product3_admin ,name="ficha_product3_admin"),
    path('ficha_product3_client',ficha_product3_client ,name="ficha_product3_client"),
    path('ficha_product4_admin',ficha_product4_admin ,name="ficha_product4_admin"),
    path('ficha_product4_client',ficha_product4_client ,name="ficha_product4_client"),
    path('ficha_product5_admin',ficha_product5_admin ,name="ficha_product5_admin"),
    path('ficha_product5_client',ficha_product5_client ,name="ficha_product5_client"),
    path('ficha_product6_admin',ficha_product6_admin ,name="ficha_product6_admin"),
    path('ficha_product6_client',ficha_product6_client ,name="ficha_product6_client"),
    path('Historial_de_compra',Historial_de_compra ,name="Historial_de_compra"),
    path('historial_ventas',historial_ventas ,name="historial_ventas"),
    path('home',home ,name="home"),
    path('impFactura',impFactura ,name="impFactura"),
    path('index_admin',index_admin ,name="index_admin"),
    path('index',index ,name="index"),
    path('login_admin',login_admin ,name="login_admin"),
    path('login',login ,name="login"),
    path('man_bod',man_bod ,name="man_bod"),
    path('man_prod',man_prod ,name="man_prod"),
    path('mockadmin',mockadmin ,name="mockadmin"),
    path('mon_compra',mon_compra ,name="mon_compra"),
    path('perfil',perfil ,name="perfil"),
    path('price',price ,name="price"),
    path('product_admin',product_admin ,name="product_admin"),
    path('product_anon', product_anon,name="product_anon"),
    path('product_client',product_client ,name="product_client"),
    path('registro_usuarios',registro_usuarios ,name="registro_usuarios"),
    path('useradmin',useradmin ,name="useradmin"),
    path('vehiculo_ficha', vehiculo_ficha,name="vehiculo_ficha"),
    path('vehiculo_tienda',vehiculo_tienda ,name="vehiculo_tienda"),
    path('vehiculo',vehiculo ,name="vehiculo")
]


