# Generated by Django 4.1a1 on 2022-06-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoriaProducto',
            fields=[
                ('idCategoriaProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoría Producto')),
                ('nombreCategoriaProducto', models.CharField(max_length=8, verbose_name='Nombre de la categoría Producto')),
            ],
        ),
        migrations.CreateModel(
            name='manProducto',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ID PRODUCTO')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Producto')),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('precio', models.CharField(max_length=10, null=True, verbose_name='Precio')),
                ('descuentoSub', models.CharField(max_length=3, verbose_name='Descuento Sub')),
                ('descuentoOfe', models.CharField(max_length=3, verbose_name='Descuento Oferta')),
                ('imagen', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen')),
                ('categoria_man', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoriaproducto')),
            ],
        ),
    ]
